var Block_Tileset =
{ "columns":4,
 "image":"Block_Tileset.png",
 "imageheight":2056,
 "imagewidth":2060,
 "margin":0,
 "name":"Block_Tileset",
 "spacing":4,
 "tilecount":12,
 "tiledversion":"1.9.2",
 "tileheight":512,
 "tiles":[
        {
         "id":0,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":385.333333333333,
                     "id":1,
                     "name":"Death",
                     "rotation":0,
                     "visible":true,
                     "width":229.666666666667,
                     "x":142.666666666667,
                     "y":126.666666666667
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":1,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"",
                     "height":512,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":512,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":2,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":512,
                     "id":2,
                     "name":"Ground",
                     "rotation":0,
                     "visible":true,
                     "width":512,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":3,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":175,
                     "id":1,
                     "name":"Death",
                     "rotation":0,
                     "visible":true,
                     "width":511,
                     "x":1,
                     "y":337
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":4,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":512,
                     "id":1,
                     "name":"Ground",
                     "rotation":0,
                     "visible":true,
                     "width":512,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }],
 "tilewidth":512,
 "type":"tileset",
 "version":"1.9"
}